### ISSUE TITLE
Bugs and recommendations 

### ISSUE THREAD

**Issue by denisde4ev** [KebabLord/teriyaki#2]
Bugs:
1. Don't use variable without quotes as it can match globbing (files with star, question mark, etc.) and be word splitting (by space tab or new line). -> _can't send file with '?*' or 'foo <tab><new line>bar' file names_
2. Tilde shroud not be in quotes. ...`"~/.ssh`... even if is just example
3.  Use double dash -- for end of argument -> _cant send file by giving file name '--help'_

_use [shellcheck](https://www.shellcheck.net) for help in fixing most bugs_

Highly recommend:
- Don't use eval, it can be made to work by quoting `"${1@Q}"` , but this only supports newer versions of bash and its better to provide the command instead of eval.

Recommend:
1. Use lower case variable names, this is the convention, upper cased comes from OS and the shell.
2. Use `[[` insted of `[` as its better syntax allows arguments without quotes

**Comment by KebabLord** [comment]
considering them as bugs is wrong since you **can**, same as what you use for most of bash tools. See _[character escaping](https://tldp.org/LDP/abs/html/escapingsection.html)_

```
λ touch "po?*p"
λ teriyaki push po\?\*p /sdcard/tmp2
po?*p                    100%    0     0.0KB/s   00:00    

λ touch "file name"
λ teriyaki push file\?name /sdcard/tmp2
file name                100%    0     0.0KB/s   00:00 
```
Also using tilde doesn't matter since the string containing it will be executed, it just works fine. And for the sake of aestheticism its unnecessary to replace it. Suggestion of use of linter tools will be considered.
